# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Display.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MainPage
import Database

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(698, 613)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(0, 0, 181);")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(130, 100, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(220, 270, 261, 41))
        self.textBrowser_2.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.BackButton = QtWidgets.QPushButton(Form)
        self.BackButton.setGeometry(QtCore.QRect(500, 530, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BackButton.setObjectName("BackButton")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(220, 340, 261, 41))
        self.textBrowser_3.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(220, 410, 261, 41))
        self.textBrowser_4.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.textBrowser_4.setObjectName("textBrowser_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        j = temp

        print(j)
        k = Database.show_one_display(j,0)
        self.textBrowser.print_(k)
        self.BackButton.clicked.connect(self.openMainPage)

    def openMainPage(self):
             self.Form2 = QtWidgets.QWidget()
             self.ui = MainPage.Ui_MainPage()
             self.ui.setupUi(self.Form2)
             self.Form2.show()
             #Form.close()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BackButton.setText(_translate("Form", "BACK TO MAIN PAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
